### ISSUE TITLE
Automate populating people in the database

### ISSUE THREAD

**Issue by olucode** [vunderkind/gf-backend#4]
To achieve this (on the backend), the major components we'd need;

## Users table (obviously)
This can contain 
* username, 
* password, 
* email/phone number (?), 
* role (we can set this to 'verifier' by default). Not sure we need it tbh

## Login auth mechanism for admin
JWT should be fine for authentication.
Justin would populate the db by generating username/password locally.

We need an enpoint for this (user creation), there should probably be a 'super-admin' account that's seeded into the db, so that only the super-admin can create admins.

## Dashboard
Only JWT authenticated users should be able to update the DB from the Dashboard.
The enpoint for updating people is already available we would only need to add JWT authentication to that endpoint.

**Comment by oreHGA** [comment]
I think #5 will address some functionality here
